### ISSUE TITLE
Makefile Issue With Three Assembly Files

### ISSUE THREAD

**Issue by CrimsonMaple** [CrimsonMaple/RenNand#1]
Makefile won't make Reboot.bin, and Payloads.h by extension, while we have SVCBackdoor.bin. Looks like a Bin2C issue.

**Comment by Reisyukaku** [comment]
`@armips $< ` means use first dependency
`@armips $(word 3,$^)` means use 3rd dependency (because $^ targets all the dependencies and word 3 picks the 3rd one)

therefore second isnt being compiled.. i just did (kinda hacky):
```
@armips $(word 1,$^)
@armips $(word 2,$^)
@armips $(word 3,$^)
```

**Comment by CrimsonMaple** [comment]
Awesome! I'll fix this right away! Or just replace it with the new update. Whatever works lol.

**Comment by CrimsonMaple** [comment]
Fixed with latest commit! ^^
